### ISSUE TITLE
Errors when running test_data with SLURM

### ISSUE THREAD

**Issue by bxuecarnegie** [transXpress/transXpress-snakemake#21]
Hi,

When trying to run the test_data on our slurm servers, we got errors at random read_partitions while others ran through without any. I've pasted all related slurm output of one partition below.

$ more trinity_parallel009*
::::::::::::::
trinity_parallel009.log
::::::::::::::
::::::::::::::
trinity_parallel009.log.slurm.err
::::::::::::::
Workflow defines that rule trinity_inchworm_chrysalis is eligible for caching between workflows (use the --cache argument to enable this).
Building DAG of jobs...
Traceback (most recent call last):
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/__init__.py", line 704, in snakemake
    keepincomplete=keep_incomplete,
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/workflow.py", line 667, in execute
    dag.init()
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 715, in update
    progress=progress,
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 792, in update_
    file.inventory()
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/io.py", line 210, in inventory
    self._local_inventory(cache)
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/io.py", line 224, in _local_inventory
    with os.scandir(path) as scan:
FileNotFoundError: [Errno 2] No such file or directory: 'trinity_out_dir/read_partitions/Fb_0/CBin_0/c48.trinity.reads.fa.out/chrysalis'
::::::::::::::
trinity_parallel009.log.slurm.out
::::::::::::::
$
$ more trinity_parallel053*
::::::::::::::
trinity_parallel053.log
::::::::::::::
::::::::::::::
trinity_parallel053.log.slurm.err
::::::::::::::
Workflow defines that rule trinity_inchworm_chrysalis is eligible for caching between workflows (use the --cache argument to enable this).
Building DAG of jobs...
Traceback (most recent call last):
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/__init__.py", line 704, in snakemake
    keepincomplete=keep_incomplete,
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/workflow.py", line 667, in execute
    dag.init()
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 715, in update
    progress=progress,
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 792, in update_
    file.inventory()
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/io.py", line 210, in inventory
    self._local_inventory(cache)
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/io.py", line 224, in _local_inventory
    with os.scandir(path) as scan:
FileNotFoundError: [Errno 2] No such file or directory: 'trinity_out_dir/read_partitions/Fb_0/CBin_0/c48.trinity.reads.fa.out'
::::::::::::::
trinity_parallel053.log.slurm.out
::::::::::::::
$
$ more trinity_parallel161*
::::::::::::::
trinity_parallel161.log
::::::::::::::
::::::::::::::
trinity_parallel161.log.slurm.err
::::::::::::::
Workflow defines that rule trinity_inchworm_chrysalis is eligible for caching between workflows (use the --cache argument to enable this).
Building DAG of jobs...
Traceback (most recent call last):
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/__init__.py", line 704, in snakemake
    keepincomplete=keep_incomplete,
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/workflow.py", line 667, in execute
    dag.init()
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 177, in init
    job = self.update(self.file2jobs(file), file=file, progress=progress)
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 715, in update
    progress=progress,
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/dag.py", line 792, in update_
    file.inventory()
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/io.py", line 210, in inventory
    self._local_inventory(cache)
  File "/work/DPB/.conda/envs/bio/lib/python3.6/site-packages/snakemake/io.py", line 224, in _local_inventory
    with os.scandir(path) as scan:
FileNotFoundError: [Errno 2] No such file or directory: 'trinity_out_dir/read_partitions/Fb_0/CBin_0/c48.trinity.reads.fa.out/chrysalis'
::::::::::::::
trinity_parallel161.log.slurm.out
::::::::::::::

We tried to troubleshoot on our server side but failed to pinpoint why only a random subset would error out. Any suggestions?

Best,
Bo

**Comment by tomas-pluskal** [comment]
Occasionally the Trinity jobs may crash due to the node running out of memory (especially if many other jobs run on the cluster and memory consumption is somewhat unpredictable). You can try using the `--restart-times 3` parameter to automatically repeat failing jobs.

Does the test run finish without problems when you run it locally?

**Comment by bxuecarnegie** [comment]
Thanks for the response. I'll see if restarting works. I have yet to run it locally on our servers so I'll be testing that as well.
One other thing. For some read partitions where the ".Trinity.fasta" file is not generated. I tried running Trinity directly with the parameter '--verbose' added and '--full_cleanup' removed. I noticed that it would generate an empty "Trinity.tmp.fasta" file in the output folder but no "Trinity.fasta" file is generated. Is this normal behavior?

**Comment by tomas-pluskal** [comment]
That is a question for Trinity authors, but I would say if the "Trinity.fasta" file is not generated, it means the Trinity run failed.

**Comment by bxuecarnegie** [comment]
Hi Tomas,

We've resolved the issues on the Trinity end. Also had to install a missing dependency (tidyverse for R) to resolve another running issue.
I'll be closing this issue for now.

Thanks,
Bo

**Comment by tomas-pluskal** [comment]
Which step in the pipeline requires tidyverse?

Tomas

**Comment by bxuecarnegie** [comment]
trinity_stats, I think it's one of Trinity's scripts that needs it.

Bo

**Comment by tomas-pluskal** [comment]
Thanks!

Tomas
